# fly.toml app configuration file generated for psa-agent-backend on 2025-07-22T11:55:03-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'psa-agent-backend'
primary_region = 'sjc'

[build]
  dockerfile = 'Dockerfile'

[deploy]
  release_command = "python -c 'print(\"Backend deployment complete\")'"

[env]
  HOST = '0.0.0.0'
  PORT = '8000'
  PYTHONPATH = '/app'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
